### ISSUE TITLE
Get rid of redundant libraries like scipy

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#15]
**Is your feature request related to a problem? Please describe.**
Currently some implementations use libraries for computations on CPU like scipy. 

**Describe the solution you'd like**
Refactor the code in such a way that it will work without them.

**Comment by denproc** [comment]
SciPy library is used in order to calculate square root of matrix (`scipy.linalg.sqrtm` @ FID) and to work with graphs (`scipy.sparse` @ MSID).

One could replace `scipy.linalg.sqrtm` with custom implementation using Newton-Schulz approach as @zakajd mentioned [here](https://github.com/photosynthesis-team/photosynthesis.metrics/pull/21).

Pytorch sparse API  is currently experimental and may change in the near future ([link](https://pytorch.org/docs/stable/sparse.html)). Therefore, scipy is still required to date.

**Comment by snk4tr** [comment]
As discussed with @denproc and @zakajd, `scipy` and `gudhi` will be removed as dependencies because they are used only in `gs`.
**To remember**: check tests

**Comment by denproc** [comment]
Hi Guys,
The MSID also uses copy library. I suggest to add try-raise to `msid.py`.

**Comment by denproc** [comment]
@zakajd will fix it today
