### ISSUE TITLE
The batch_size may influence the result.

### ISSUE THREAD

**Issue by jinxiqinghuan** [photosynthesis-team/piq#281]
I found that when I test the same data set, my batch-size is different, which may cause the final index to be different. 
For example the PSNR.

**Comment by zakajd** [comment]
Hi @jinxiqinghuan 
Can you please provide a minimal working example that demonstrates this bug?

**Comment by zakajd** [comment]
Can you also specify how large is the difference between runs with different batch sizes? 
It may be possible that due to `reduction='mean'` flag values are reduced _slightly_ differently for each batch and thus result in non-identical metric values.
Try to run PSNR with `reduction='none'` and verify that individual values are the same.

**Comment by jinxiqinghuan** [comment]
Hi, @zakajd Thanks for your answer. I have found the problem, it is not caused by piq. Thank you again for your kindness.
