### ISSUE TITLE
Bug in __version_tuple function

### ISSUE THREAD

**Issue by Volodimirich** [photosynthesis-team/piq#289]
Bug in __version_tuple() function, for pytorch version 1.10.0a0+ecc3718
 
1. Install last pytorch version, I met this bug in google colab
2. Use srssim.
3. Function will fall, because can't cast string with letters to 

Screenshot:
![photo_2022-02-03_22-28-21](https://user-images.githubusercontent.com/55362016/152424886-6f9fa671-ef7e-415c-8abb-1e2d96e49fe6.jpg)

**Comment by zakajd** [comment]
Thanks for reporting! 
@snk4tr can you please take a look?

**Comment by snk4tr** [comment]
@zakajd I'm on it 👍

**Comment by snk4tr** [comment]
The problem is that this string is not a valid [semver](https://semver.org/) version. It seems that PyTorch follows a much broader versioning protocol [PEP-440](https://www.python.org/dev/peps/pep-0440/) and uses versions from the broader scope for automated releases (such as [NGC container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-07.html) ones). I am implementing a broader parser to handle that.

**Comment by snk4tr** [comment]
Lol, it is even funnier. Actually, PEP 440 versions do not include all valid Simver versions and vice versa e.g.:
- `"1.2.3-alpha.1.2+build.11.e0f985a"` is a valid Semver but not PEP 440
- `"1.10.0a0+ecc3718"` is a valid PEP 440 but not Semver

Hence, since PyTorch mixes up both systems, we gotta have parsers for both systems.
