### ISSUE TITLE
Can't understand the benchmark table

### ISSUE THREAD

**Issue by jasony93** [photosynthesis-team/piq#354]
I appreciate for this great work first of all.

I was looking at the benchmark table where you use SRCC values obtained with PIQ and reported in surveys.

There are two values in each cell, but from my understanding the first value is SRCC calculated from PIQ metric and surveys.

If that is the case, what does the second value represent?

Is it SRCC calculated from survey AND survey...?

Or have I not understood correctly?

Thank in advance.

**Comment by denproc** [comment]
Hi @jasony93,
Thank you for raising the question. 
As you pointed out, each cell contains two values of SRCC. The first value is an SRCC estimation using the PIQ implementation of the metric on one of the available benchmark datasets. The second value is a reference SRCC value reported in the original paper describing the method or evaluation surveys.
Having these two values, we show that PIQ implementation matches or is close to the performance reported in the paper/survey or original implementations in Matlab.

Hope it helps to navigate the benchmark results. Otherwise, just let us know about any other concerns you may have.

**Comment by jasony93** [comment]
It helped, but honestly I am still confused.

When I read about what SRCC is, I understood it as ranking correlation between two variables,

and in this case, I think the two variables are: one being people's evaluation and the other being whatever metric we want to 
use.

So, the first value is an SRCC estimation using the PIQ implementation AND people's evaluation...?

and the second value is an SRCC estimation using the method proposed in the original paper AND people's evaluation...?

Another question on my mind is that, in the case of BRISQUE, it seems that there is a huge gap between the two variables, which means there is a trend that two methods are in disagreement. Is this a good sign because the PIQ implementation made an improvement from the traditional method, OR is this a bad sign because the PIQ implementation was not able to capture the analogy of the traditional method?

**Comment by jasony93** [comment]
That helped me a lot.
Thank you very much!

**Comment by jasony93** [comment]
That helped me a lot.
Thank you very much!
