### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by PavelOstyakov** [photosynthesis-team/piq#82]
Currently, there are two issues:

1) photosynthesis_metrics is a really long name. In #74, you rename long file names. But how about the library itself?
2) The package names in import statements and pip are different: photosynthesis_metrics vs photosynthesis-metrics. This does not allow identifying it automatically in IDE and installing it in one click.

So, I suggest considering renaming it before it's too late :)

**Comment by snk4tr** [comment]
Hi @PavelOstyakov.
In general I think that both suggestions are good. 
We will discuss the first one internally and see whether we come up with some reasonable alternative.
We will definitely fix the second point since it leads to inconvenience.

**Comment by snk4tr** [comment]
We decided on the name **piq** which stands for PyTorch Image Quality because of the following reasons:
- It is easy to import since it is just 3 letters long
- It is easy to remember since it reflects what it is used for 
- There is no such package in pip at the moment
- If we decide to extend our work and create similar repo with metrics in Keras or TF it will also be a decent choice to name them **kiq** and **tiq** respectively

Going to create a PR on that soon
